### ISSUE TITLE
Works with vsync?

### ISSUE THREAD

**Issue by irscy** [theyareonit/Click-Between-Frames#15]
Something feels really off when playing with vsync on 60hz. I'm curious as to if it still functions with it enabled? I don't believe it's placebo

**Comment by PaniniLinguini** [comment]
You shouldn't be using the in-game vsync setting ever it's complete trash

**Comment by PaniniLinguini** [comment]
I felt really bad about saying that without elaborating, so I decided to write the bible.

Firstly, vsync is a confusing term. The vsync setting in Geometry Dash is weird, makes no sense, and is completely useless. Even worse, the "presentation modes" are all called random shit in the Nvidia control panel for non-vulkan games, so there is absolutely no question you will be incredibly confused by this. You can find non-ambiguous terms here: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkPresentModeKHR.html
basic explanation:
VRR: Freesync/Gsync; if you have this, your monitor can run in a range of refresh rates called the VRR range; for example, mine is 48-240hz.
Immediate: This does not prevent tearing at all; partially rendered frames are drawn on top of the old frames. This can be good at high framerates and is technically the best option, but it is barely better than VRR+mailbox when you're in the VRR range. It's also useless when you're in the VRR range, so you inherently want Mailbox.
Fifo: Terrible
Mailbox: Sends the newest complete frame to be displayed. If you have fluctuating frame rates, this will cause stuttering, as you can have jitter.

To simplify this, visually inspect your game while it's running **with vsync off**, **making sure it's taking up the entire screen**, to determine if you see tearing (partial frames). If you don't care, Mailbox is probably the setting you want anyway, and if you see no tearing, it's working.

Second, you need to find out which multiple of display refresh rate * an integer your computer can handle and doesn't cause stutter or dropped frames.
For example, if you are on 60hz, see if you can maintain a 60*2=120fps cap on a highly detailed level, then a 240fps cap, etc.

Finally, here are the settings you should use depending on your preferences and availability of VRR:
If you have VRR:
You should cap your fps to your (display's refresh rate * integer) but subtract 1 or 2.
For example, my setup is 240hz: 479fps, in-game vsync off.

If you don't have VRR:
You should cap your fps to your display's refresh rate * integer so it's more likely the frames are generated at a good time (when your monitor is ready to display another frame).

No VRR and no mailbox:
Here, you want very high framerates and all vsync off. This is probably impractical for Geometry Dash and will look stupid, especially if you're getting less than 1000fps or something ridiculous.

You can find this backed up by BlurBusters:
![image](https://github.com/theyareonit/Click-Between-Frames/assets/135870218/5a2c4302-3e8d-4eb6-8b7f-7db93e3cce8b)
https://blurbusters.com/gsync/gsync101-input-lag-tests-and-settings/6/

Unfortunately, he uses ambiguous terminology like vsync, so it's confusing. Also, the diagram shows a straight, clean tear line, which is possible to achieve with what is called "half vsync" or "adaptive sync" (both terribly ambiguous terms). However, these are rarely implemented anywhere, so in reality, your tear lines will be diagonal and weird. Regardless, any tearing will look especially bad in geometry dash because it's 2D.

If you actually read and comprehend this unsolicited, unhinged rant, I will be very surprised. I would be glad to help you make your game run better, so if you need any help changing these settings, just ask; I could even have you share your screen if you'd like.

**Comment by PaniniLinguini** [comment]
I thought geometry dash was directx? anyways, I was just using the vulkan present modes to explain the different types of vsync. This mod works great and chances are he has lag because he has his settings wrong.

**Comment by irscy** [comment]
The issue was also discord overlay  wtf I forgot about this thread
