### ISSUE TITLE
What exactly does late input cutoff do?

### ISSUE THREAD

**Issue by EESports7** [theyareonit/Click-Between-Frames#16]
I've read the info box but I'm confused about what "precision" means specifically.

**Comment by theyareonit** [comment]
It controls where in the frame the mod checks for inputs. If disabled, the mod will check for inputs at the start of the frame. If enabled, the mod will check for inputs right before physics calculations are done.

Enabling this setting gives worse input precision because the amount of time between the start of the frame and the start of physics calculations is highly variable, especially on laggy levels or bad PCs. However, it will give less input lag, because the cutoff for inputs is at a later point.

Disabling the setting will generally give very high precision, since the time that each frame starts is very predictable.
