### ISSUE TITLE
[SUGGESTION] Add to Android

### ISSUE THREAD

**Issue by LumerGD120** [theyareonit/Click-Between-Frames#39]
Can you please add it to android thank you.

**Comment by OM3GA6400** [comment]
> Can you please add it to android thank you.

(based on what i know) the reason this mod exists is because mice and keyboards have higher hz and therefor faster response time, mobile screen are are much more limited in there response time and detect inputs at the same rate they refresh (so if your phone runs 60 fps its also 60 hz) BTW this is just what i found online so i could be wrong

**Comment by OM3GA6400** [comment]
so it just wouldn't do anything on android

**Comment by JerichoGesolgani** [comment]
> mobile screen are are much more limited in there response time and detect inputs at the same rate they refresh 
according to my research it's said that mobile doubles sometimes triple their refresh rate i could be wrong too but idk
