### ISSUE TITLE
Incompatible with Wave Trail Drag Fix?

### ISSUE THREAD

**Issue by edwloef** [theyareonit/Click-Between-Frames#4]
![image](https://github.com/theyareonit/Click-Between-Frames/assets/75493688/7b0a001e-5bdb-44c7-930c-42dae3c51220)

https://github.com/nytelytee/geode-wave-trail-drag-fix

**Comment by NegativePremium** [comment]
It might work with an older version of the mod

**Comment by nytelytee** [comment]
It has manually been set as incompatible because of a mistake I made in my mod that only really became apparent when this mod came out. In CBF 1.0.2 it has been changed to incompatible with <= 1.1.6, which is the latest version of WTDF that's on the index. I am in the process of fixing it; once WTDF updates, it will work with CBF.

**Comment by edwloef** [comment]
Alright, thanks for the notice! :)
